version: "3"

services:
  web:
    container_name: web
    image: nginx:1.20
    volumes:
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
      - .:/var/www/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - PHP_INDEX=index.php
      - PHP_FPM_HOST=php
      - PHP_FPM_PORT=9000

  php:
    container_name: php
    image: asimlqt/php-fpm:8.0
    volumes:
      - .:/var/www/html

