version: "3"

services:
  web:
    container_name: web
    image: nginx:1.13
    volumes:
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    - .:/var/www/html
    ports:
    - "80:80"
    environment:
    - NGINX_PORT=80
    - PHP_INDEX=index.php
    - PHP_FPM_HOST=php
    - PHP_FPM_PORT=9000
    command: /bin/sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  php:
    container_name: php
    image: asimlqt/php-fpm:7.1
    volumes:
    - .:/var/www/html
